volumes:
  pg_data:
  static_volume:
  media_volume:
  frontend_volume:

services:
  db:
    image: postgres:13.0-alpine
    container_name: foodgram_db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env

  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/foodgram_backend:latest  # ЗАМЕНИТЬ
    container_name: foodgram_backend
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/foodgram_frontend:latest  # ЗАМЕНИТЬ
    container_name: foodgram_frontend
    command: >
      sh -c "
        cp -rf /usr/share/nginx/html/* /var/html/frontend/ &&
        chown -R 101:101 /var/html/frontend/ &&
        chmod -R 755 /var/html/frontend/ &&
        echo 'Frontend structure:' &&
        find /var/html/frontend/ -type f -name '*.js' -o -name '*.css' | head -10
      "
    volumes:
      - frontend_volume:/var/html/frontend/
    restart: "no"

  nginx:
    image: ${{ secrets.DOCKER_USERNAME }}/foodgram_nginx:latest  # ЗАМЕНИТЬ
    container_name: foodgram_nginx
    ports:
      - "85:80"
    volumes:
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - frontend_volume:/var/html/frontend/
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
      - frontend
    restart: always
