volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.0-alpine
    container_name: foodgram_db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file: .env
  
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: foodgram_backend
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
      #- ./load_data.py:/app/load_data.py:ro
      #- ./load_data.py:/app/create_test_data.py:ro
    depends_on:
      - db
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    container_name: foodgram_frontend
    command: >
      sh -c "
        mkdir -p /var/html/static &&
        cp -rf /usr/share/nginx/html/* /var/html/static/ &&
        chown -R 101:101 /var/html/static/ &&  # nginx user UID:GID
        chmod -R 755 /var/html/static/ &&
        ls -la /var/html/static/
      "
    volumes:
      - static:/var/html/static/
    restart: "no"

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    container_name: foodgram_nginx
    ports:
      - "85:80"
    volumes:
      - static:/var/html/static/
      - media:/var/html/media/
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - backend
      - frontend
    restart: always