volumes:
  pg_data:
  static_volume:
  media_volume:
  frontend_volume:

services:
  db:
    image: postgres:13.0-alpine
    container_name: foodgram_db
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data/
    env_file:
      - ./infra/.env

  backend:
    image: slaize19/foodgram_backend:fixed
    container_name: foodgram_backend
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./infra/.env
    command: "gunicorn config.wsgi:application --bind 0.0.0.0:9000"

  frontend:
    image: slaize19/foodgram_frontend:latest
    container_name: foodgram_frontend
    volumes:
      - frontend_volume:/var/html/frontend/
    restart: "no"

  nginx:
    image: slaize19/foodgram_nginx:latest
    container_name: foodgram_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
      - frontend_volume:/var/html/frontend/
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: always
