volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  foodgram_backend:
    image: ${DOCKER_USERNAME}/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db

    command: >
      sh -c "
        echo 'Ждем запуска базы данных...' &&
        while ! python -c \"import socket; socket.create_connection(('db', 5432), timeout=1)\" 2>/dev/null; do
          sleep 1
        done &&
        echo 'База данных запущена!' &&
        python manage.py migrate &&
        python manage.py collectstatic --noinput &&
        gunicorn foodgram_backend.wsgi:application --bind 0.0.0.0:9000
      "

  foodgram_frontend:
    image: ${DOCKER_USERNAME}/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
      - media_volume:/app/media 

  foodgram_nginx:
    image: ${DOCKER_USERNAME}/foodgram_nginx
    env_file: .env

    volumes:
      - static_volume:/staticfiles/
      - media_volume:/app/media 
    ports:
      - "85:80"
    depends_on:
      - foodgram_backend
      - foodgram_frontend
