services:
  db:
    image: postgres:13-alpine
    container_name: foodgram-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: foodgram
      POSTGRES_USER: foodgram_user
      POSTGRES_PASSWORD: your_secure_password_123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U foodgram_user -d foodgram"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: foodgram-backend
    restart: always
    volumes:
      - static_volume:/app/collected_static
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - DOCKER_CONTAINER=True

  nginx:
    image: nginx:1.25-alpine
    container_name: foodgram-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/var/html/static
      - media_volume:/var/html/media
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
